version: '3.1'

services:
  db: 
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=spring
      - POSTGRES_DB=spring
      - POSTGRES_PASSWORD=1234
